name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3 # For making HTTP requests
  shared_preferences: ^2.0.7 # For saving and loading simple data locally
  crypto: ^3.0.2 # For cryptographic algorithms
  encrypt: ^5.0.1 # For encryption and decryption
  # qrscan: ^2.0.0
  # qrscan: ^0.3.3
  flutter_barcode_scanner: ^2.0.0


  cupertino_icons: ^1.0.2 # For iOS style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # For recommended linting rules

flutter:
  uses-material-design: true
